WebThietBiDienTu/Controllers/DatHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebThietBiDienTu.Models;

namespace WebThietBiDienTu.Controllers
{
    public class DatHangController : Controller
    {
        //
        // GET: /DatHang/

        DataClasses1DataContext data = new DataClasses1DataContext();

        public ActionResult ThemMatHang(int msp)
        {
            GioHang gio = (GioHang)Session["gh"];
            if (gio == null)
            {
                gio = new GioHang();
            }
            gio.them(msp);
            Session["gh"] = gio;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult XemGioHang()
        {
            GioHang gh = (GioHang)Session["gh"];
            return View(gh);
        }

        [HttpGet]
        public ActionResult XacNhanDonHang()
        {
            //Kiểm tra khách hàng đăng nhập
            KhachHang khach = Session["kh"] as KhachHang;

            if (khach == null) //Khách hàng chưa đăng nhập
            {
                return RedirectToAction("DangNhap", "KhachHang");
            }

            //Khách hàng đăng nhập thành công
            ViewBag.k = khach;

            GioHang gio = Session["gh"] as GioHang;
            return View(gio);
        }

        [HttpPost]
        public ActionResult LuuDonHang(FormCollection c)
        {
            string ngaygiao = c["txtDate"];

            KhachHang khach = Session["kh"] as KhachHang;

            GioHang gio = Session["gh"] as GioHang;

            //Lưu 1 dòng tin vào bảng HoaDon (ngày hóa đơn, mã khách hàng, ngày giao)
            DonHang hd = new DonHang();
            hd.NgayDat = DateTime.Now;
            hd.MaKH = khach.MaKH;
            hd.NgayGiao = DateTime.Parse(ngaygiao);
            data.DonHangs.InsertOnSubmit(hd);
            data.SubmitChanges();

            //Lưu nhiều dòng tin vào bảng ChiTiet (mã hóa đơn, mã sản phẩm, số lượng)
            foreach (CartItem it in gio.dsSP)
            {
                ChiTietDonHang ct = new ChiTietDonHang();
                ct.MaDonHang = hd.MaDonHang;
                ct.MaSP = it.iMaSP;
                ct.SoLuong = it.iSL;

                data.ChiTietDonHangs.InsertOnSubmit(ct);
                data.SubmitChanges();
            }

            Session["gh"] = null;

            return View();
        }

        public ActionResult XoaGioHang()
        {
            Session["gh"] = null;
            return RedirectToAction("Index", "Home");
        }

    }
}

WebThietBiDienTu/Views/DatHang/XacNhanDonHang.cshtml
@using WebThietBiDienTu.Models
@{
    ViewBag.Title = "XacNhanDonHang";
    Layout = "~/Views/Shared/_LayoutHienThi.cshtml";
    KhachHang a = ViewBag.k;
}

@model GioHang

<form action="/DatHang/LuuDonHang" method="post">
    <h2>THÔNG TIN ĐẶT HÀNG</h2>
    <table style="display: inline;" class="text-left">
        <tr>
            <td>Họ tên: @a.HoTen </td>
            <td>Điện thoại: @a.DienThoai </td>
        </tr>
        <tr>
            <td colspan="2" class="text-left">Địa chỉ: @a.DiaChi </td>
        </tr>
        <tr>
            <td>Ngày đặt: @DateTime.Now.ToShortDateString()</td>
            <td>Ngày giao:
                <input type="date" name="txtDate" />
            </td>
        </tr>
        <tr>
            <td>&nbsp; </td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2" class="text-center">
                <table class="table" style="display: inline">
                    <tr>
                        <td colspan="4" class="text-danger">Thông tin đơn hàng </td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm </td>
                        <td>Hình ảnh</td>
                        <td>Số lượng </td>
                        <td>Đơn giá </td>
                    </tr>
                    @foreach (CartItem item in Model.dsSP)
                    { 
                        <tr>
                            <td>@item.iTenSP </td>
                            <td>
                                <img style="width: 220px; height: 200px;" src="~/Content/image/@item.HinhAnh" />
                            </td>
                            <td>@item.iSL </td>
                            <td>@item.iGia </td>
                        </tr>
                    }
                    <tr>
                        <td colspan="2">Tổng số lượng: @Model.TongSL() </td>
                        <td colspan="2">Tổng tiền: @Model.TongThanhTien() </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Xác nhận đặt hàng" />
            </td>
        </tr>
    </table>
</form>

WebThietBiDienTu/Views/DatHang/XemGioHang.cshtml
@using WebThietBiDienTu.Models;
@{
    ViewBag.Title = "XemGioHang";
    Layout = "~/Views/Shared/_LayoutHienThi.cshtml";
}

@model GioHang

@if (Model == null)
{
    <h2>Giỏ hàng trống</h2>
    <a class="nav-link" style="border-radius: 120px; background: #2c82dd; color: white; text-align: center" href="@Url.Action("Index", "Home")">Mua hàng nào</a>
}
else
{
    
    
    
    <table class="table" style="text-align: center;">
    <tr>
        <th> Tên sản phẩm </th>
        <th> Ảnh </th>
        <th style="width: 120px"> Số Lượng </th>
        <th> Đơn Giá </th>
        <th style="width: 150px"> Thành Tiền </th>
        <th> </th>
        <th> </th>
    </tr>
    @foreach (CartItem item in Model.dsSP)
    {
        <tr>
            <td> @item.iTenSP </td>
            <td><img style="width: 220px; height: 200px;" src="~/Content/image/@item.HinhAnh" /></td>
            <td>@item.iSL</td>
            <td> @item.iGia </td>
            <td> @item.ThanhTien </td>
            <td> <a href="#"> Xóa </a> </td>
            <td> <a href="#" class="btn btn-secondary"> Sửa </a> </td>
        </tr>
    }
      <tr>
          <td colspan="3"> TỔNG </td>

          <td class="text-danger text-bold"> @Model.TongSL() </td>
          <td> </td>
          <td class="text-danger text-bold"> @String.Format("{0:#,##}", Model.TongThanhTien())</td>
          <td>
              @Html.ActionLink("Xóa giỏ hàng", "XoaGioHang", "DatHang", new{@class="btn btn-danger"})
          </td>
          <td colspan="2">
              @Html.ActionLink("Đặt hàng", "XacNhanDonHang", "DatHang", new{@class="btn btn-danger"})
          </td>
      </tr>
</table>
} 