WebThietBiDienTu/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebThietBiDienTu.Models;

namespace WebThietBiDienTu.Controllers
{
    public class KhachHangController : Controller
    {
        //
        // GET: /KhachHang/

        DataClasses1DataContext data = new DataClasses1DataContext();

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection c)
        {
            string ten = c["txtName"];
            string mk = c["txtPass"];
            KhachHang khach = data.KhachHangs.SingleOrDefault(t => t.TaiKhoan == ten && t.MatKhau == mk);
            if (khach == null)
                return View();
            Session["kh"] = khach;
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult CreateAccount()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAccount(FormCollection col)
        {
            string tenkh = col["txtHoTen"];
            string ngaysinh = col["dtpNgaySinh"];
            string gt = col["GioiTinh"];
            string sdt = col["txtSDT"];
            string dc = col["txtDC"];
            string tk = col["txtTaikhoan"];
            string ps = col["txtPass"];
            string email = col["txtEmail"];
            KhachHang kh = new KhachHang();
            kh.HoTen = tenkh;
            kh.GioiTinh = gt;
            kh.DienThoai = sdt;
            kh.DiaChi = dc;
            kh.TaiKhoan = tk;
            kh.MatKhau = ps;
            kh.Email = email;
            kh.NgaySinh = DateTime.Parse(ngaysinh);
            data.KhachHangs.InsertOnSubmit(kh);
            data.SubmitChanges();
            Session["KH"] = kh;
            KhachHang k = (KhachHang)Session["KH"];
            return RedirectToAction("Index", "Home");
        }
    }
}

WebThietBiDienTu/Views/KhachHang/CreateAccount.cshtml
@using WebThietBiDienTu.Models;
@{
    Layout = null;
    Layout = "~/Views/Shared/_LayoutHienThi.cshtml";
}

<!DOCTYPE html>
<div class="container">
    <h2>Đăng ký</h2>
    <div class="loginbox">
        <form action="~/KhachHang/AddAccount" method="post" onsubmit="return FormRe()">
            <p>
                <input class="form-control" name="txtHoTen" type="text" id="txtHoTen" placeholder="Họ tên" />
            </p>
            <div class="form-inline">
                <div class="col">
                    Ngày Sinh &nbsp;&nbsp;
                    <input class="form-control" style="width: 170px;" name="dtpNgaySinh" type="date" id="dtpNgaySinh" />
                </div>
                <div class="col">
                    Giới Tính &nbsp;&nbsp;
                    <select class="form-control" style="width: 80px;" name="GioiTinh">
                        <option>Nam</option>
                        <option>Nữ</option>
                    </select>
                </div>
            </div>
            <br />
            <p>
                <input class="form-control" name="txtEmail" aria-describedby="emailHelp" type="email" id="txtEmail" placeholder="Email" />
            </p>
            <p>
                <input class="form-control" name="txtSDT" type="text" id="txtSDT" placeholder="Số điện thoại" />
            </p>
            <p>
                <input class="form-control" name="txtDC" type="text" id="txtDC" placeholder="Địa chỉ" />
            </p>
            <p>
                <input class="form-control" name="txtTaikhoan" type="text" id="txtTaikhoan" placeholder="Tài khoản đăng nhập" />
            </p>
            <p>
                <input class="form-control" name="txtPass" type="password" placeholder="Password" id="txtPass" />
            </p>
            <br />

            <button style="border-radius: 120px;" type="submit" class="btn btn-primary" id="btnAdd">Đăng ký</button>
            <br />
            <br />

        </form>
    </div>
</div>
<script language="javascript">
    function FormRe() {

        var acc = document.getElementById('txtTaikhoan').value;
        var pass = document.getElementById('txtPass').value;
        var email = document.getElementById('txtEmail').value;
        var sdt = document.getElementById('txtSDT').value;
        var dtpNgaySinh = document.getElementById('dtpNgaySinh').value;
        var txtDC = document.getElementById('txtDC').value;
        var hoten = document.getElementById('txtHoTen').value;
        // Bước 2: Kiểm tra dữ liệu hợp lệ hay không

        if (acc == '') {
            alert('Bạn chưa nhập tên đăng nhập');
        }
        else
            if (pass == '') {
                alert('Bạn chưa nhập mật khẩu');
            }
            else if (email == '') {
                alert('Bạn chưa nhập email');
            }
            else if (sdt == '') {
                alert('Bạn chưa nhập số điẹn thoại');
            }
            else if (txtDC == '') {
                alert('Bạn chưa nhập địa chỉ ');
            }
            else if (hoten == '') {
                alert('Bạn chưa nhập tên ');
            }
            else if (dtpNgaySinh == '') {
                alert('Bạn chưa nhập ngày sinh ');
            }
            else {
                alert('Dữ liệu hợp lệ!!!');
                return true;
            }
        return false;
    }
</script>

WebThietBiDienTu/Views/KhachHang/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_LayoutHienThi.cshtml";
}

<div class="container" style="text-align: center">
    <form action="/KhachHang/DangNhap" method="post">
        <p style="color: #056bf7; font-size: 17px;">ĐĂNG NHẬP TÀI KHOẢN</p>
        <p>Nhập tài khoản và mật khẩu của bạn</p>
        <p>
            <input class="form-control" type="text" name="txtName" placeholder="Tên đăng nhập"/>
        </p>
        <p>
            <input class="form-control" type="password" name="txtPass" placeholder="Mật khẩu"/>
        </p>
        Khách hàng mới? <a href="@Url.Action("CreateAccount", "KhachHang")">Đăng ký</a>
        <p>
            <input type="submit" value="Đăng nhập" />
        </p>
    </form>
</div>